Update README.md
Takhmina175/Newsweek_ClonePage pull request #1
Opened 2020-10-12 19:13 UTC by sumon0002001

2020-10-12 21:15 UTC, sumon0002001 commented
**ADDED HTML, CSS AND BOOTSTRAP**
-HTML
-CSS
-Bootstrap4
This Website is about making a clone page of Newsweek.

2020-10-12 23:19 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @sumon0002001 and @Takhmina175! Thanks for submitting your code!

:100: the website follow the structure of the original
:100: The website has all the elements as the original
:100: The website is responsive

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Edit the PR message so it contains a descriptive PR.
![image](https://user-images.githubusercontent.com/25774518/95792626-87115b00-0ca9-11eb-9ae1-383bfc948647.png)

- [x] The PR should be more descriptive than the one you have in a comment below.
![image](https://user-images.githubusercontent.com/25774518/95792642-8f699600-0ca9-11eb-9ad9-4c6b1963c92f.png)

- [ ] Ensure that all linter checks pass before submitting for a re-review. Right now it doesn't pass.

- [ ] Improve the commit messages and commit ofter.

- [ ] Give one new line space between rules in the CSS file and maintain the consistency through the file

- [ ] Use semantic HTML for the main section ```<main>``` as the project uses in the nav and footer.

- [ ] the original doesn't take 100% width in screens larger than 1312px
![image](https://user-images.githubusercontent.com/25774518/95797397-12dcb480-0cb5-11eb-979b-cbc8965220ca.png)

- [ ] Nav doesn't look as original in desktop view
https://microverse.zoom.us/j/5156882051?pwd=UE92N3prSkQxVXBwR0pjeHR5SzFFUT09

- [ ] The debate section doesn't look as expected in desktop view
![image](https://user-images.githubusercontent.com/25774518/95797605-85e62b00-0cb5-11eb-8144-3eb8b5a32e7d.png)

- [ ] Elements doesn't look as expected
![image](https://user-images.githubusercontent.com/25774518/95797680-b7f78d00-0cb5-11eb-9b81-ef45befd1e82.png)

- [ ] image is distorted.
![image](https://user-images.githubusercontent.com/25774518/95797703-c80f6c80-0cb5-11eb-83f3-463a28b1ac18.png)

- [ ] Newsletter section doesn't look as expected
![image](https://user-images.githubusercontent.com/25774518/95797783-fc832880-0cb5-11eb-9f56-de2b9faef682.png)

- [ ] Section doesn't look as expected in tablet view
![image](https://user-images.githubusercontent.com/25774518/95797838-1d4b7e00-0cb6-11eb-957c-aa368c41a82b.png)

- [ ] Element doesn't look as expected in tablet view
![image](https://user-images.githubusercontent.com/25774518/95797911-466c0e80-0cb6-11eb-9a9b-a1d1827bbf38.png)

- [ ] Element doesn't look as expected
![image](https://user-images.githubusercontent.com/25774518/95797931-5552c100-0cb6-11eb-86af-a0ba83b8c96c.png)

- [ ] Element doesn't look as expected
![image](https://user-images.githubusercontent.com/25774518/95797997-774c4380-0cb6-11eb-88fe-4aeab69194a9.png)

- [ ] Navbar doesn't look as original in mobile version
![image](https://user-images.githubusercontent.com/25774518/95798054-9519a880-0cb6-11eb-9353-d632e7495674.png)

- [ ] Navbar overlaps title for Top stories
![image](https://user-images.githubusercontent.com/25774518/95798092-a9f63c00-0cb6-11eb-9d78-5c5040d39f6d.png)

- [ ] Title is not aligned
![image](https://user-images.githubusercontent.com/25774518/95798134-c3978380-0cb6-11eb-8959-97972f870dd3.png)

- [ ] Element doesn't looks as original
![image](https://user-images.githubusercontent.com/25774518/95798156-d6aa5380-0cb6-11eb-9d4b-89a11e2b17f8.png)

- [ ] Sections missing: Us, World, Business... etc
![image](https://user-images.githubusercontent.com/25774518/95798214-f477b880-0cb6-11eb-95e8-9e2eaa31f0da.png)

- [ ] email element look distorted.
![image](https://user-images.githubusercontent.com/25774518/95798286-27ba4780-0cb7-11eb-8ae3-caee34fbe0d8.png)


### [OPTIONAL]  :yellow_circle:  


### [Comments] :green_circle: 

- A great tool to test in the website looks as intended in different screen sizes is to use the browsers media query inspector. Please use it to inspect the site and compare it against the original.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-13 16:05 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are still some issues that need to be addressed before we can move forward. Please review the list below. **Do not submit for a re-review until the changes are made**.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] Improve the preview screenshot in the readme
![image](https://user-images.githubusercontent.com/25774518/95884292-89bf8f00-0d41-11eb-8907-e00b612d876b.png)

- [x] Update the title of the PR for something more meaningful and descriptive

- [x] Navbar is missing date in desktop view
![image](https://user-images.githubusercontent.com/25774518/95884897-487baf00-0d42-11eb-9408-2b4603ec3873.png)

- [ ] Link to live preview is not updated in README

> ## Required changes 
> ### [Mandatory] 
> * [x]  Edit the PR message so it contains a descriptive PR.
>   ![image](https://user-images.githubusercontent.com/25774518/95792626-87115b00-0ca9-11eb-9ae1-383bfc948647.png)
> * [x]  The PR should be more descriptive than the one you have in a comment below.
>   ![image](https://user-images.githubusercontent.com/25774518/95792642-8f699600-0ca9-11eb-9ad9-4c6b1963c92f.png)
> * [x]  Ensure that all linter checks pass before submitting for a re-review. Right now it doesn't pass.
> * [x]  Improve the commit messages and commit ofter.
> * [x]  Give one new line space between rules in the CSS file and maintain the consistency through the file
- [ ]  **Use semantic HTML for the main section `<main>` as the project uses in the nav and footer.**
- [ ]  **the original doesn't take 100% width in screens larger than 1312px**
>   ![image](https://user-images.githubusercontent.com/25774518/95797397-12dcb480-0cb5-11eb-979b-cbc8965220ca.png)
- [ ]  **Nav doesn't look as original in desktop view**

- [ ]  **The debate section doesn't look as expected in desktop view**
>   ![image](https://user-images.githubusercontent.com/25774518/95797605-85e62b00-0cb5-11eb-8144-3eb8b5a32e7d.png)
- [ ]  **Elements doesn't look as expected. NOW the element is missing**
>   ![image](https://user-images.githubusercontent.com/25774518/95797680-b7f78d00-0cb5-11eb-9b81-ef45befd1e82.png)
- * [ ]  **image is distorted.**
>   ![image](https://user-images.githubusercontent.com/25774518/95797703-c80f6c80-0cb5-11eb-83f3-463a28b1ac18.png)
- [ ]  N**ewsletter section doesn't look as expected**
>   ![image](https://user-images.githubusercontent.com/25774518/95797783-fc832880-0cb5-11eb-9f56-de2b9faef682.png)
- [ ]  Section doesn't look as expected in tablet view
>   ![image](https://user-images.githubusercontent.com/25774518/95797838-1d4b7e00-0cb6-11eb-957c-aa368c41a82b.png)
- [ ]  **Element doesn't look as expected in tablet view**
>   ![image](https://user-images.githubusercontent.com/25774518/95797911-466c0e80-0cb6-11eb-9a9b-a1d1827bbf38.png)
- [ ]  **Element doesn't look as expected**
>   ![image](https://user-images.githubusercontent.com/25774518/95797931-5552c100-0cb6-11eb-86af-a0ba83b8c96c.png)
- [ ]  **Element doesn't look as expected**
>   ![image](https://user-images.githubusercontent.com/25774518/95797997-774c4380-0cb6-11eb-88fe-4aeab69194a9.png)
- [ ]  **Navbar doesn't look as original in mobile version**
>   ![image](https://user-images.githubusercontent.com/25774518/95798054-9519a880-0cb6-11eb-9353-d632e7495674.png)
- [ ]  **Navbar overlaps title for Top stories**
>   ![image](https://user-images.githubusercontent.com/25774518/95798092-a9f63c00-0cb6-11eb-9d78-5c5040d39f6d.png)
- [ ]  **Title is not aligned**
>   ![image](https://user-images.githubusercontent.com/25774518/95798134-c3978380-0cb6-11eb-8959-97972f870dd3.png)
- [ ]  **Element doesn't looks as original**
>   ![image](https://user-images.githubusercontent.com/25774518/95798156-d6aa5380-0cb6-11eb-9d4b-89a11e2b17f8.png)
- [ ]  **Sections missing: Us, World, Business... etc**
>   ![image](https://user-images.githubusercontent.com/25774518/95798214-f477b880-0cb6-11eb-95e8-9e2eaa31f0da.png)
- [ ]  **email element look distorted.**
>   ![image](https://user-images.githubusercontent.com/25774518/95798286-27ba4780-0cb7-11eb-8ae3-caee34fbe0d8.png)
> 
> ### [OPTIONAL] 
> ### [Comments] 
> * A great tool to test in the website looks as intended in different screen sizes is to use the browsers media query inspector. Please use it to inspect the site and compare it against the original.
> 
> ## Keep up the great work  and Happy Coding  !!

2020-10-13 17:46 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

**I must say, you've done an amazing job so far. However, there are some required changes to be fixed before this project can be approved. Please check my points below and fix them as appropriate.**

**[ REQUIRED CHANGES ]**

_Please note that apart from the main point of this project (using bootstrap), this review will be based on the fact that you are asked to be more precise and to make sure that your page looks exactly the same as the source page._

- [x] There is a very glaring difference between the color of your Newsweek header and the original color, as seen in the image below. Please use a similar color.

Original Page:
![18-11-07](https://user-images.githubusercontent.com/26856491/95893205-8b0fac80-0d7f-11eb-8d73-0541c5f4f0ef.png)

Your page:
![18-10-44](https://user-images.githubusercontent.com/26856491/95893222-906cf700-0d7f-11eb-9a02-7c541c19f331.png)

- [ ] You have still not updated the title of your Pull Request. This is very important. Check the image below on how to update the title of your PR.

![pr](https://user-images.githubusercontent.com/26856491/95893380-ca3dfd80-0d7f-11eb-922b-50e6d0a75dc3.png)

**On medium screen sizes**

- [ ] There are some articles after the `Opinion` section, before the `In the magazine` section. These articles should not be here, based on the view from the original page.
- What I'm saying is, for this screen size, the `Opinion` section should be immediately followed by the `In the magazine` section.
- This is also happening at small screen sizes.

Original page:
![18-31-08](https://user-images.githubusercontent.com/26856491/95895305-5fda8c80-0d82-11eb-955c-98d5cb3d4617.png)

Your page:
![18-30-35](https://user-images.githubusercontent.com/26856491/95895324-6832c780-0d82-11eb-95dd-86d82a88c7b2.png)

- [ ] Since the `Sign up` section highlighted in the image below is present in your project, set it to be in the center.

Original page:
![18-35-32](https://user-images.githubusercontent.com/26856491/95895665-e8592d00-0d82-11eb-9128-11ee15135a92.png)

Your page:
![18-35-03](https://user-images.githubusercontent.com/26856491/95895672-ebecb400-0d82-11eb-9302-ef4648e6fb8a.png)

- [ ] Adjust the height of the newsletter image on the `Newsletter` section of your page.

| Original | Clone (your page) |
| -------------- | --------------- |
| ![18-43-36](https://user-images.githubusercontent.com/26856491/95896355-0a06e400-0d84-11eb-8b92-c8bf5b1a694c.png) | ![18-42-56](https://user-images.githubusercontent.com/26856491/95896399-13904c00-0d84-11eb-9217-9bda677031f9.png) |

**Comments**
- In your README.md file, I can see that the address bar and the taskbar of your screen captured with the screenshot of the project. Just like the last reviewer mentioned, personally, I also think you should crop away your taskbar and the browser address bar from the screenshot.
- We're almost there, do not give up on this project. It's a large project and most of these changes cannot be figured out once because most times, one change leads to another.

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-13 19:44 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Great job implementing the changes. However, there are still a few fixes needed.**

1). **The navigation bar for the desktop screen size**

original | clone
---------| -------
![nav_original](https://user-images.githubusercontent.com/38922385/95902368-65919b80-0d9d-11eb-8e44-08d90da3b8f3.png) | ![nav_clone](https://user-images.githubusercontent.com/38922385/95902406-717d5d80-0d9d-11eb-94e8-dfbaa4c68b3e.png)

- **Please fix your navbar to look like the original.**

- **The navbar background color and Newsweek logo background color should match like in the original.**

- **The two bottom navbars are missing on your page.**

2). **The signup form is no longer showing on your page for desktop screen size(>992px). Please add it. Also, change the design in the medium and small screen sizes so it looks like the original.**

![signup_original](https://user-images.githubusercontent.com/38922385/95904079-ae4a5400-0d9f-11eb-88b7-610ce4660c40.png)

3). **A few changes requested by the previous tse have not been implemented yet. Check the screenshot below.**

![prev_review](https://user-images.githubusercontent.com/38922385/95907493-4e09e100-0da4-11eb-99aa-6382ddaceb7f.png)


4). **The sections,(u.s, world, business, tech&science, culture and sports), between the editor's pick and subscribe block are missing on your page on small screen sizes.**

5). **Crop out the taskbar and the browser address bar from the readme file screenshot.**

6). **Add the .DS-store in the .gitignore file since it is not related to the project.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-10-13 20:02 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team, 

**Please make the changes requested above. In case of anything, you can reach me on slack (Rose Wanjohi).**

### Happy coding 😃.

2020-10-13 20:45 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**I apologize for my previous review. It was based on the Newsweek branch instead of the feature branch.**

**You have made all changes but there are a few still needed before the project is approved.**

1). **On 992px width, some content in the mid navbar section is displaying on two lines instead of one line like in the original. Example tech & science.**

![midnav_clone](https://user-images.githubusercontent.com/38922385/95912890-1bfc7d00-0dac-11eb-950e-7279c16be133.png)

2). **The three bottom images in the u.s, world, business, tech&science, culture and sports sections, are not well aligned on small screen sizes. Here is an example.**

![us_clone](https://user-images.githubusercontent.com/38922385/95913234-99c08880-0dac-11eb-9ed3-86f9c6428efd.png)

3). **Implement the following change requested by the previous tse.**

![newsletter_clone](https://user-images.githubusercontent.com/38922385/95913697-51ee3100-0dad-11eb-931f-2f32f17ee146.png)

4).  **Add the .DS-store file and node_modules folder in the .gitignore file. They are not supposed to be committed as a requirement by Microverse.**

2020-10-14 00:32 UTC, Rhelli requested changes
# Changes Required 🛑♻️

Hi guys, excellent job on the project so far. It's fully responsive and stays true to Newsweeks original design. There are however a few outstanding changes that are required in order to approve this project. Let's get them sorted so you can complete this project and move onto the next one!

### Mandatory Changes
 1. **[Mandatory]** - At present, your opinions section appears to flow straight into a duplicated section instead of 'More Stories'.

**Newsweeks website** 👇🏽

![image](https://user-images.githubusercontent.com/48107460/95928533-810a9f80-0db9-11eb-803d-aa44ea91c51d.png)

**Your version of Newsweek** 👇🏽

![image](https://user-images.githubusercontent.com/48107460/95928631-c62ed180-0db9-11eb-83b7-58cc964e37ec.png)

**Fix:** Your version of Newsweek _does_ have the 'More Stories' section, all you need to do is get rid of this duplicated section. This is appearing on small screen sizes.

******
 2. **[Mandatory]** - The image in the following 'Sign Up' area is broken and the `alt` text is displaying where it should not.

**Here is your version** 👇🏽
![image](https://user-images.githubusercontent.com/48107460/95928981-b2379f80-0dba-11eb-983d-56ef31a2d6ca.png)

**Here is Newsweeks version** 👇🏽
![image](https://user-images.githubusercontent.com/48107460/95929009-c4b1d900-0dba-11eb-9165-fd0bccd595ce.png)

**Fix:** In your HTML (line 321) you have wrapped the `img` tag inside of a `label` tag. I suspect if you separate them, it will solve this (if it is not an error to do with the path to the image or an error with the image itself)

******

3. **[Mandatory]** - Your subscribe section images and texts are overlapping each other making the text unreadable. This occurs on both small and medium-size screens

**Small Screen Size** 👇🏽
![image](https://user-images.githubusercontent.com/48107460/95929245-6cc7a200-0dbb-11eb-9741-9a7c91984726.png)

**Medium Screen Size** 👇🏽
![image](https://user-images.githubusercontent.com/48107460/95929327-a00a3100-0dbb-11eb-8b04-c994ab31e359.png)

**Fix:** Place the text in its own container and place it beneath the magazine images. If it is still overlapping, check the entire subscribe container height to ensure it is not squeezing all its contents into too small a space (causing overlapping).

*****

4. **[Mandatory]** - Please check the text alignment with the images below

**Your version of Newsweek** 👇🏽
![image](https://user-images.githubusercontent.com/48107460/95929503-10b14d80-0dbc-11eb-82a4-8e6fecccf432.png)


**Newsweeks version** 👇🏽
![image](https://user-images.githubusercontent.com/48107460/95929519-1dce3c80-0dbc-11eb-8e9e-cc4b9895eb5b.png)

**Fix:** Convert (if not already) each container holding the image and the headline to flex. Then give that container the property of `flex-direction: row`. That should ensure the text aligns to the right of the image, not beneath it.

****** 

As I said, an excellent job so far on the project, so don't be disheartened by the requested changes. Get them fixed and you'll be on to the next project in no time!

If you have any extra questions or need any help, @ me here on Github or get in contact with me via Slack and I'll do what I can to help.

All the best,

Rory

2020-10-14 06:24 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ] Please update the title of PR. 
![95893380-ca3dfd80-0d7f-11eb-922b-50e6d0a75dc3](https://user-images.githubusercontent.com/58504655/95946769-a8d42480-0e06-11eb-840d-6898bfc1225f.png)

- [ ] Fix: Convert (if not already) each container holding the image and the headline to flex. Then give that container the property of flex-direction: row. That should ensure the text aligns to the right of the image, not beneath it.


- [ ] top navbar should be sticky and decrease its width on scrolling. 

**Clone**

![chrome-capture (31)](https://user-images.githubusercontent.com/58504655/95945950-023b5400-0e05-11eb-8a06-007ada647fd6.jpg)

**Original**

![chrome-capture (32)](https://user-images.githubusercontent.com/58504655/95946115-521a1b00-0e05-11eb-8534-6ccc782b5105.jpg)

- [ ] In editor's pick every item is aligned in a row but on your clone,

**Clone**

![chrome-capture (32)](https://user-images.githubusercontent.com/58504655/95946258-9efdf180-0e05-11eb-8934-5fb7825b944f.jpg)
 there is an alignment error. Please have a look below. 

**Original**

![chrome-capture (33)](https://user-images.githubusercontent.com/58504655/95946288-ad4c0d80-0e05-11eb-8e92-91395a58eef1.jpg)

- [ ] Width of left side items should be equal to right side items. Please have a look below. 

**Clone**

![chrome-capture (34)](https://user-images.githubusercontent.com/58504655/95946388-df5d6f80-0e05-11eb-9166-5ee5ab1e131e.jpg)

**Original**

![chrome-capture (35)](https://user-images.githubusercontent.com/58504655/95946422-ed12f500-0e05-11eb-970b-140aa26ed5d3.jpg)

- [ ] Newsletter and subscribe section should have equal width. Please have a look below. 

**Clone**

![chrome-capture (36)](https://user-images.githubusercontent.com/58504655/95946631-60b50200-0e06-11eb-84a7-878a4bad888d.jpg)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-14 09:02 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ] Please change Learning Twitter’s Bootstrap framework by building a site that actually uses it – Newsweek. #1 to  Building 
with Bootstrap

- [ ] As described earlier, please make the navbar sticky. Please scroll the [original page](https://www.newsweek.com/) to get more understanding. 

- [ ]  The images in the webpage are not rendering.
 
![chrome-capture (40)](https://user-images.githubusercontent.com/58504655/95964703-8819c800-0e22-11eb-88f7-11b294cb9dd5.jpg)

![chrome-capture (38)](https://user-images.githubusercontent.com/58504655/95964482-4852e080-0e22-11eb-8eae-6eb22c1d7ee9.jpg)
![chrome-capture (39)](https://user-images.githubusercontent.com/58504655/95964579-66b8dc00-0e22-11eb-9ad9-cb15219f1551.jpg)

- [ ] As I cannot see the images, I cannot review your project completely. Please resolve that issue. And most importantly work on all the changes requested in previous reviews. 

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
>            <a href="#"><img src="images/footer-logo.png" alt="newsweek bg-danger logo"></a>
logo Image is not working

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
> +                      <input  class="w-75  mb-3 mx-auto email" type="text" placeholder="Email Adress">
Please add padding around these and align them correctly as present on the original page.

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
> +                    <img class="w-100 h-100 newletter-pic" src="images/newsletter-img.png" alt="newletter-pic">
Please add padding around these and align them correctly as present on the original page.

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
> +                    <img class="w-100 h-100 newletter-pic" src="images/newsletter-img.png" alt="newletter-pic">
Image is not working

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
> +              <section class="container-fluid mb-5">
Please add padding around these and align them correctly as present on the original page.

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
>                      <button class="subs-btn text-white bg-danger pt-1 pb-1 pl-1 pr-1 primary-font font-weight-bolder border rounded-sm" type="submit">SUBSCRIBE ></button>
Please add padding around these and align them correctly as present on the original page.

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
>                     </div>
Please add padding around these and align them correctly as present on the original page.

2020-10-14 09:02 UTC, arslanbisharat commented on index.html
> +                    <a href="#"><img class="float-left pr-3 bilden" src="images/business-5.webp" alt="two presidents"></a>
Image not working

2020-10-14 10:42 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Well done @team :clap: :clap: :clap:, thanks for making the required changes :toolbox: by the previous TSE's.

now you can merge, your project is approved.

## Happy Coding :tophat:

2020-10-14 10:48 UTC, merged